/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3039",
        "on-primary-container": "#eeefff",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-container": "#bdffdb",
        "surface-container": "#ededf9",
        "surface-tint": "#0053db",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#38485d",
        "secondary": "#505f76",
        "primary": "#004ac6",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-high": "#e7e7f3",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary": "#006242",
        "on-secondary-container": "#54647a",
        "background": "#faf8ff",
        "surface-container-low": "#f3f3fe",
        "on-secondary": "#ffffff",
        "on-background": "#191b23",
        "tertiary-fixed": "#6ffbbe",
        "secondary-container": "#d0e1fb",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-surface": "#191b23",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-primary": "#b4c5ff",
        "tertiary-container": "#007d55",
        "on-error-container": "#93000a",
        "on-surface-variant": "#434655",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "primary-fixed-dim": "#b4c5ff",
        "outline": "#737686",
        "secondary-fixed": "#d3e4fe",
        "surface-variant": "#e1e2ed",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "surface-dim": "#d9d9e5",
        "outline-variant": "#c3c6d7",
        "surface-container-highest": "#e1e2ed",
        "on-primary-fixed-variant": "#003ea8",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "base": "4px",
        "xs": "4px",
        "gutter": "24px",
        "max-width": "1440px",
        "md": "16px",
        "2xl": "48px",
        "margin": "32px",
        "xl": "32px",
        "lg": "24px",
        "sm": "8px",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
